//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Execute
    {
        public int proposal { get; set; }
        public Nullable<int> department { get; set; }
        public int register { get; set; }
        public string content { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Result Result { get; set; }
        public virtual Proposal Proposal1 { get; set; }
    }
}
