//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASP_testEntities2 : DbContext
    {
        public ASP_testEntities2()
            : base("name=ASP_testEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Teacher_type> Teacher_type { get; set; }
        public virtual DbSet<Execute> Execute { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Proposal_type> Proposal_type { get; set; }
        public virtual DbSet<Jointly> Jointly { get; set; }
        public virtual DbSet<Proposal> Proposal { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
